(define (turn-and-walk dir n)
  (turn dir)
  (walk n))

(walk)
(turn-and-walk 'left 4)
(turn-and-walk 'left 10)
(turn-and-walk 'left 2)
(turn-and-walk 'left 7)
(turn-and-walk 'right 8)
(turn-and-walk 'right 7)
(turn-and-walk 'right 2)
(turn-and-walk 'right 5)
(turn-and-walk 'left 4)
(turn-and-walk 'left 5)
(turn-and-walk 'left 2)
(turn-and-walk 'left 3)
